[workspace]
members = ["krill-frost"]
resolver = "3"

[workspace.package]
authors = ["JamiiDao <support@jamiidao.app>"]
version = "0.1.0"
license = "AGPL-3.0"
description = "Institution grade server for Solana onchain tokenization, attestation and stablecoins"
readme = "./README.md"
keywords = [
    "solana",
    "solana-pay",
    "onchain-attestation",
    "tokenization",
    "wallet-adapter",
]
categories = ["cryptography::cryptocurrencies"]
edition = "2021"

[workspace.dependencies]
bitcode = { version = "0.6.7" }
blake3 = "1.8.3"
thiserror = { version = "2.0.17", default-features = false }
zeroize = { version = "1.8.2", default-features = false }
rand_chacha = { version = "0.9", features = ["os_rng"] }
async-dup = "1.2.4"
async-lock = "3.4.2"
smol = "2.0.2"
dirs = "6.0.0"
fjall = { version = "3.0.1", default-features = false }

# quinn = { version = "=0.11.9", default-features = false, features = [
#     "runtime-smol",
#     "rustls",
# ], optional = true }
